accumulate_grad_batches: 1
amp_backend: native
amp_level: O2
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
benchmark: false
check_val_every_n_epoch: 1
checkpoint_callback: true
config_file: config.yaml
dataset: Cifar10
debug: false
default_root_dir: null
deterministic: false
distributed_backend: null
early_stop_callback: false
fast_dev_run: false
gpus: &id001 !!python/name:pytorch_lightning.trainer.trainer._gpus_arg_default ''
gradient_clip_val: 0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
load_checkpoint_file: null
log_dir: lightning_logs
log_gpu_memory: null
log_save_interval: 100
logger: true
max_epochs: 1000
max_steps: null
min_epochs: 1
min_steps: null
mode: train
model: bert
no_cuda: false
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
num_workers: 8
optimizer: SGD
optimizer_cosine_lr: true
optimizer_decay_at_epochs:
- 80
- 150
- 250
optimizer_decay_with_factor: 10.0
optimizer_learning_rate: 0.1
optimizer_momentum: 0.9
optimizer_warmup_ratio: 0.05
optimizer_weight_decay: 0.0001
overfit_batches: 0.0
overfit_pct: null
precision: 32
prepare_data_per_node: true
pretrained_model_dir: models
process_position: 0
profiler: null
progress_bar_refresh_rate: 1
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_ckpt: null
resume_from_checkpoint: null
row_log_interval: 50
seed: 2021
sync_batchnorm: false
terminate_on_nan: false
test_percent_check: null
tpu_cores: *id001
track_grad_norm: -1
train_percent_check: null
truncated_bptt_steps: null
val_check_interval: 1.0
val_percent_check: null
weights_save_path: null
weights_summary: top
